#if !defined(AFX__BAND_H__455244F4_3C2B_4EE6_A364_E634B6946E6C__INCLUDED_)
#define AFX__BAND_H__455244F4_3C2B_4EE6_A364_E634B6946E6C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_Band wrapper class

class C_Band : public COleDispatchDriver
{
public:
	C_Band() {}		// Calls COleDispatchDriver default constructor
	C_Band(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_Band(const C_Band& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetForeColor(unsigned long newValue);
	unsigned long GetForeColor();
	void SetCaption(LPCTSTR lpszNewValue);
	CString GetCaption();
	void SetImage(const VARIANT& newValue);
	VARIANT GetImage();
	void SetRefPicture(LPDISPATCH newValue);
	VARIANT GetPicture();
	long GetPosition();
	long GetIndex();
	void SetKey(LPCTSTR lpszNewValue);
	CString GetKey();
	void SetNewRow(BOOL bNewValue);
	BOOL GetNewRow();
	void SetVisible(BOOL bNewValue);
	BOOL GetVisible();
	void SetStyle(long nNewValue);
	long GetStyle();
	void SetTag(VARIANT* newValue);
	VARIANT GetTag();
	void SetAllowVertical(BOOL bNewValue);
	BOOL GetAllowVertical();
	void SetMinWidth(float newValue);
	float GetMinWidth();
	void SetMinHeight(float newValue);
	float GetMinHeight();
	void SetWidth(float newValue);
	float GetWidth();
	void SetRefChild(LPDISPATCH newValue);
	LPDISPATCH GetChild();
	float GetHeight();
	void SetFixedBackground(BOOL bNewValue);
	BOOL GetFixedBackground();
	void SetEmbossPicture(BOOL bNewValue);
	BOOL GetEmbossPicture();
	void SetEmbossHighlight(unsigned long newValue);
	unsigned long GetEmbossHighlight();
	void SetEmbossShadow(unsigned long newValue);
	unsigned long GetEmbossShadow();
	void SetUseCoolbarPicture(BOOL bNewValue);
	BOOL GetUseCoolbarPicture();
	void SetUseCoolbarColors(BOOL bNewValue);
	BOOL GetUseCoolbarColors();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__BAND_H__455244F4_3C2B_4EE6_A364_E634B6946E6C__INCLUDED_)
