#if !defined(AFX__BANDS_H__6593A436_C8C7_40AD_ABDE_D1EE3509DBF4__INCLUDED_)
#define AFX__BANDS_H__6593A436_C8C7_40AD_ABDE_D1EE3509DBF4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_Band;

/////////////////////////////////////////////////////////////////////////////
// C_Bands wrapper class

class C_Bands : public COleDispatchDriver
{
public:
	C_Bands() {}		// Calls COleDispatchDriver default constructor
	C_Bands(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_Bands(const C_Bands& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	C_Band Add(long Index, LPCTSTR Key, LPCTSTR Caption, const VARIANT& Image, BOOL NewRow, const VARIANT& Child, BOOL Visible);
	void Remove(const VARIANT& Index);
	void Clear();
	C_Band GetItem(const VARIANT& Index);
	long GetCount();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__BANDS_H__6593A436_C8C7_40AD_ABDE_D1EE3509DBF4__INCLUDED_)
