// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_bands.h"

// Dispatch interfaces referenced by this interface
#include "_band.h"


/////////////////////////////////////////////////////////////////////////////
// C_Bands properties

/////////////////////////////////////////////////////////////////////////////
// C_Bands operations

C_Band C_Bands::Add(long Index, LPCTSTR Key, LPCTSTR Caption, const VARIANT& Image, BOOL NewRow, const VARIANT& Child, BOOL Visible)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_BSTR VTS_VARIANT VTS_BOOL VTS_VARIANT VTS_BOOL;
	InvokeHelper(0x6003000b, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Index, Key, Caption, &Image, NewRow, &Child, Visible);
	return C_Band(pDispatch);
}

void C_Bands::Remove(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6003000c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Index);
}

void C_Bands::Clear()
{
	InvokeHelper(0x6003000d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

C_Band C_Bands::GetItem(const VARIANT& Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index);
	return C_Band(pDispatch);
}

long C_Bands::GetCount()
{
	long result;
	InvokeHelper(0x6803000a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}
