#if !defined(AFX__COOLBAR_H__1B692241_54DA_4B7F_8174_FEE9EDF2D3CF__INCLUDED_)
#define AFX__COOLBAR_H__1B692241_54DA_4B7F_8174_FEE9EDF2D3CF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;
class C_Bands;

/////////////////////////////////////////////////////////////////////////////
// C_CoolBar wrapper class

class C_CoolBar : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_CoolBar)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x38911d92, 0xe448, 0x11d0, { 0x84, 0xa3, 0x0, 0xdd, 0x1, 0x10, 0x41, 0x59 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetRefPicture(LPDISPATCH newValue);
	CPicture GetPicture();
	void SetForeColor(unsigned long newValue);
	unsigned long GetForeColor();
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetEmbossHighlight(unsigned long newValue);
	unsigned long GetEmbossHighlight();
	void SetEmbossShadow(unsigned long newValue);
	unsigned long GetEmbossShadow();
	void SetEmbossPicture(BOOL bNewValue);
	BOOL GetEmbossPicture();
	C_Bands GetBands();
	long GetRowCount();
	void SetRefImageList(LPDISPATCH newValue);
	LPDISPATCH GetImageList();
	void SetFixedOrder(BOOL bNewValue);
	BOOL GetFixedOrder();
	void SetBandBorders(BOOL bNewValue);
	BOOL GetBandBorders();
	void SetVariantHeight(BOOL bNewValue);
	BOOL GetVariantHeight();
	void SetOrientation(long nNewValue);
	long GetOrientation();
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	long GetHwnd();
	CPicture GetMouseIcon();
	void SetRefMouseIcon(LPDISPATCH newValue);
	long GetMousePointer();
	void SetMousePointer(long nNewValue);
	void OLEDrag();
	void Refresh();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__COOLBAR_H__1B692241_54DA_4B7F_8174_FEE9EDF2D3CF__INCLUDED_)
